### ISSUE TITLE
Query doesn't get replaced - SOLVED please archieve/delte

### ISSUE THREAD

**Issue by Hhhannahhh** [sowdust/searchbook#12]
I've been trying to get Searchbook to work for quite a while now, at first the red search bar would appear, but the results shown were still the ones for the random query I typed (scrolling didn't help). This was a week ago, I tried to figure out what I was doing wrong again today with the same result but now even the red "query interecpted" bar is missing. I tried copy and pasting the queries from the readme file, tried changing my language, nothing provided any results. I only ever got as far as Searchbook providing me with the user ID and me setting the query. What else could I be doing wrong? Thanks for all your work!

**Comment by slayerutica** [comment]
Since you said you've been having this issue for a week now, the developer made a few edits about 4 days ago. I had issues about 3 days ago and went to read comments to see if there were changes and noticed the developer's comment on the code page that was only a day old at the time so I assumed that was likely why my version was no longer working correctly. I just deleted the version I had downloaded a couple weeks ago and then re-download the zip file and reinstalled it to Firefox. It works great again. But the issues you are describing are ones I experienced at the time as well.

**Comment by Hhhannahhh** [comment]
Really embarassed now because that actually did the trick! Feeling incredibly stupid for not figuring out that there was an updated version lol Thanks so much, slayerutica!

**Comment by slayerutica** [comment]
You're very welcome Hhhannahhh. And don't feel bad. I yelled my computer screen for about 10 minutes and wanted to cry before I realized there was a recent comment with an update lol

**Comment by sowdust** [comment]
glad you resolved it. from the latest version, there is a notification system that warns you with a red banner if your version is not up to date.
